export const source = [
  { name: 'And good luck incoming Seniors!' },
  { name: 'This is just the beginning!' },
  { name: 'Adjoa Quansah ("Best dancer")' },
  { name: 'Alissa Colascione ("Best smile and caring mom")' },
  { name: 'Andrew Vuong ("Secretly a genius")' },
  { name: 'Anna Kazannik ("Most likely to find the cleverest solutions")' },
  { name: 'Arun Kambivalappil ("IIT")' },
  { name: 'Billy Maguire ("The brother that you always want")' },
  { name: 'Carina Zhang ("Babyfox")' },
  { name: 'Catherine Straus ("Recursion queency")' },
  { name: 'Chris Bell ("Best OSU player")' },
  { name: 'Chris Lopez ("Most knowledgeable, truuee")' },
  { name: 'Chris Sorta ("Most chill")' },
  { name: 'Daniel Flores ("Gold apex player")' },
  { name: 'Elana Cohen-Khani ("Credit card queen")' },
  { name: 'Emmanuel Mota ("UFO")' },
  { name: 'Haneen Amro ("Warmest smile")' },
  { name: 'Harris Li ("Raid Boss aka. Tech lead")' },
  { name: 'Jacob Johnson ("Best V&V partner")' },
  { name: 'James Scolamieri ("Best mustache")' },
  { name: 'Jessie Wildermuth ("Best hairstyles")' },
  { name: 'Jenny Park ("Most cultured")' },
  { name: 'Johnny Tang ("Algo expert")' },
  { name: 'Jorgen Carlsen ("CS Guru, best bread maker")' },
  { name: 'Karl Mabunga ("Most likely to freeze on Zoom")' },
  { name: 'Katie Poa ("Emoji princess")' },
  { name: 'Lim Nhep' },
  { name: 'Mataeux Gauthier ("Most impressive hair")' },
  { name: 'Michael Stringer ("Secretly has a great singing voice")' },
  { name: 'Mike Zhulev ("Hidden genius")' },
  { name: 'Ryan DeCoster ("React wine god")' },
  { name: 'Shaquon Kelley ("Most creative")' },
  { name: 'Theo Nguyen ("Most likely to scare you with a ghost story")' },
  { name: 'Victoria Chen ("Most likely to start a bootcamp")' }
];
